stages:
  - test
  - commitlint
  - name: release
    if: branch = master

sudo: required
cache: bundler
language: ruby

services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: default-debian-9
    - INSTANCE: default-ubuntu-1804
    - INSTANCE: default-centos-7

script:
  - bundle exec kitchen verify ${INSTANCE}

jobs:
  include:
    # Define the commitlint stage
    - stage: commitlint
      language: node_js
      node_js: lts/*
      before_install: skip
      script:
        - npm install @commitlint/config-conventional -D
        - npm install @commitlint/travis-cli -D
        - commitlint-travis
    # Define the release stage that runs semantic-release
    - stage: release
      language: node_js
      node_js: lts/*
      before_install: skip
      script:
        - npm install @semantic-release/changelog@3 -D
        - npm install @semantic-release/exec@3 -D
        - npm install @semantic-release/git@7 -D
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release@15

